const SESSION_TTL_SECONDS = 60 * 60 * 4;
export default { async fetch(request, env) { const url = new URL(request.url); const path = url.pathname.replace(/\/+/g, '/').replace(/\/$/, ''); if (request.method === 'OPTIONS') return cors(env, new Response(null,{status:204})); try { if(path==='/login'&&request.method==='POST') return cors(env, await login(request,env)); if(path==='/verify'&&request.method==='GET') return cors(env, await verify(request,env)); if(path==='/save'&&request.method==='POST') return cors(env, await save(request,env)); return cors(env,json({error:'Not found'},404)); } catch(e){ return cors(env,json({error:String(e)},500)); } } };
async function login(req,env){const b=await req.json();if(!env.ADMIN_PASSWORD||b.password!==env.ADMIN_PASSWORD)return json({error:'Invalid password'},401);const exp=Math.floor(Date.now()/1000)+SESSION_TTL_SECONDS;return json({token:exp+'.'+await sign(String(exp),env.SESSION_SECRET),expiresIn:SESSION_TTL_SECONDS})}
async function verify(req,env){return json({ok:await valid(req,env)?true:false},await valid(req,env)?200:401)}
async function save(req,env){if(!await valid(req,env))return json({error:'Unauthorized'},401);const b=await req.json();if(b.images)for(const image of b.images){if(image.path&&image.base64)await put(env,image.path,image.base64,true,b.commitMessage||'Admin: update image')}if(b.dataJson)await put(env,'data.json',btoa(unescape(encodeURIComponent(JSON.stringify(b.dataJson,null,2)))),false,b.commitMessage||'Admin: update content');return json({ok:true})}
async function valid(req,env){const h=req.headers.get('Authorization')||'';const t=h.startsWith('Bearer ')?h.slice(7):'';if(!t.includes('.'))return false;const [exp,sig]=t.split('.');return Number(exp)>Math.floor(Date.now()/1000)&&sig===await sign(exp,env.SESSION_SECRET)}
async function sign(message,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const b=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(message));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function put(env,path,content,dataUrl,message){const api=`https://api.github.com/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/contents/${path}`;const headers={'Authorization':`Bearer ${env.GITHUB_TOKEN}`,'User-Agent':'apex-bionet-admin','Accept':'application/vnd.github+json','Content-Type':'application/json'};let sha;const old=await fetch(`${api}?ref=${env.GITHUB_BRANCH}`,{headers});if(old.ok)sha=(await old.json()).sha;const body={message,content:dataUrl?content.replace(/^data:[^,]+,/,'').split(',').pop():content,branch:env.GITHUB_BRANCH};if(sha)body.sha=sha;const r=await fetch(api,{method:'PUT',headers,body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text())}
function json(x,status=200){return new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json'}})}function cors(env,r){r.headers.set('Access-Control-Allow-Origin',env.ALLOWED_ORIGIN||'*');r.headers.set('Access-Control-Allow-Methods','GET,POST,OPTIONS');r.headers.set('Access-Control-Allow-Headers','Content-Type,Authorization');return r}
